// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExampleSentence struct {
	SentenceID    string `json:"sentenceID"`
	SentenceText  string `json:"sentenceText"`
	TranslationID string `json:"translationID"`
}

type Mutation struct {
}

type Query struct {
}

type Translation struct {
	TranslationID      string             `json:"translationID"`
	EnglishTranslation string             `json:"englishTranslation"`
	WordID             string             `json:"wordID"`
	ExampleSentences   []*ExampleSentence `json:"exampleSentences"`
}

type Word struct {
	WordID       string         `json:"wordID"`
	PolishWord   string         `json:"polishWord"`
	Translations []*Translation `json:"translations"`
}
