// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExampleSentence struct {
	SentenceID   string       `json:"sentenceID"`
	SentenceText string       `json:"sentenceText"`
	Translation  *Translation `json:"translation"`
}

type Mutation struct {
}

type Query struct {
}

type Translation struct {
	TranslationID      string             `json:"translationID"`
	EnglishTranslation string             `json:"englishTranslation"`
	Word               *Word              `json:"word"`
	ExampleSentences   []*ExampleSentence `json:"exampleSentences"`
}

type Word struct {
	WordID       string         `json:"wordID"`
	PolishWord   string         `json:"polishWord"`
	Translations []*Translation `json:"translations"`
}
